import { Meme } from './types';

export const APP_NAME = "MemeVsMeme";

export const SAMPLE_TAGS = [
  'funny',
  'programming',
  'coding',
  'javascript',
  'react',
  'angular',
  'vue',
  'typescript',
  'java',
  'python',
  'c++',
  'c#',
  'php',
  'ruby',
  'swift',
  'kotlin',
  'go',
  'rust',
  'scala',
  'haskell',
  'erlang',
  'clojure',
  'elixir',
  'dart',
  'flutter',
  'android',
  'ios',
  'mobile',
  'web',
  'design',
  'ux',
  'ui',
  'frontend',
  'backend',
  'database',
  'sql',
  'nosql',
  'mongodb',
  'postgresql',
  'mysql',
  'redis',
  'firebase',
  'aws',
  'azure',
  'gcp',
  'cloud',
  'devops',
  'security',
  'ai',
  'ml',
  'deeplearning',
  'datascience',
  'bigdata',
  'blockchain',
  'crypto',
  'nft',
  'metaverse',
  'gaming',
  'esports',
  'music',
  'movies',
  'sports',
  'news',
  'politics',
  'travel',
  'food',
  'health',
  'fitness',
  'fashion',
  'beauty',
  'diy',
  'art',
  'photography',
  'nature',
  'science',
  'history',
  'books',
  'education',
  'careers',
  'startups',
  'business',
  'marketing',
  'sales',
  'finance',
  'realestate',
  'law',
  'government',
  'nonprofit',
  'community',
  'family',
  'relationships',
  'parenting',
  'pets',
  'cars',
  'home',
  'garden',
  'cooking',
  'recipes',
  'technology',
  'innovation',
  'future',
  'inspiration',
  'motivation',
  'success',
  'leadership',
  'productivity',
  'mindfulness',
  'happiness',
  'love',
  'peace',
  'hope',
  'dreams',
  'memes'
];

export const SAMPLE_MEMES: Meme[] = [
  {
    id: '1',
    prompt: 'When the code finally works after hours of debugging',
    prompt_id: 'prompt1',
    imageUrl: '/Drake-Hotline-Bling.jpg',
    ipfsCid: '',
    caption: 'Left panel: Using console.log() | Right panel: Using a debugger',
    creatorId: '1',
    votes: 120,
    createdAt: new Date('2023-10-15'),
    tags: ['programming', 'debugging', 'drake'],
    isBattleSubmission: true,
  },
  {
    id: '2',
    prompt: 'That moment when you realize you forgot to save your work',
    prompt_id: 'prompt2',
    imageUrl: '/Two-Buttons.jpg',
    ipfsCid: '',
    caption: 'Button 1: Close without saving | Button 2: Remember you\'ve been working for hours',
    creatorId: '2',
    votes: 85,
    createdAt: new Date('2023-10-14'),
    tags: ['work', 'saving', 'buttons'],
    isBattleSubmission: true,
  },
  {
    id: '3',
    prompt: 'How I see myself in meetings',
    prompt_id: 'prompt3',
    imageUrl: '/expanding brain.png',
    ipfsCid: '',
    caption: 'Small Brain: Taking notes | Normal Brain: Asking questions | Expanding Brain: Multitasking | Galaxy Brain: Daydreaming about lunch',
    creatorId: '3',
    votes: 95,
    createdAt: new Date('2023-10-13'),
    tags: ['meetings', 'work', 'brain'],
    isBattleSubmission: false,
  },
  {
    id: '4',
    prompt: 'Software development process',
    prompt_id: 'prompt4',
    imageUrl: '/Distracted-Boyfriend.jpg',
    ipfsCid: '',
    caption: 'Boyfriend: Developers | Girlfriend: Current project | Other girl: New technology',
    creatorId: '1',
    votes: 150,
    createdAt: new Date('2023-10-12'),
    tags: ['development', 'technology', 'distracted'],
    isBattleSubmission: true,
  }
];

export const MEME_TEMPLATES = [
  { id: 'drake', name: 'Drake Hotline Bling', url: '/Drake-Hotline-Bling.jpg' },
  { id: 'buttons', name: 'Two Buttons', url: '/Two-Buttons.jpg' },
  { id: 'distracted', name: 'Distracted Boyfriend', url: '/Distracted-Boyfriend.jpg' },
  { id: 'brain', name: 'Expanding Brain', url: '/expanding brain.png' },
  { id: 'changemymind', name: 'Change My Mind', url: '/Change-My-Mind-tilt-corrected-meme-2.jpg' }
];

export const CAPTION_STYLES = [
  { id: 'funny', name: 'Funny' },
  { id: 'sarcastic', name: 'Sarcastic' },
  { id: 'dark', name: 'Dark Humor' },
  { id: 'wholesome', name: 'Wholesome' },
  { id: 'technical', name: 'Technical' }
];

export const MOCK_USERS = [
  {
    id: '1',
    username: 'memeMaster',
    avatarUrl: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=1',
    memeStreak: 15,
    wins: 42,
    losses: 12,
    level: 8,
    xp: 2450,
    createdAt: new Date('2023-08-01')
  },
  {
    id: '2',
    username: 'laughFactory',
    avatarUrl: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=2',
    memeStreak: 8,
    wins: 27,
    losses: 19,
    level: 5,
    xp: 1280,
    createdAt: new Date('2023-09-15')
  },
  {
    id: '3',
    username: 'humorHero',
    avatarUrl: 'https://api.dicebear.com/7.x/fun-emoji/svg?seed=3',
    memeStreak: 23,
    wins: 65,
    losses: 8,
    level: 12,
    xp: 4120,
    createdAt: new Date('2023-07-10')
  }
];
